name: Yggdrasil Main Pipeline

env:
  GITHUB_REGISTRY: "ghcr.io"
  GITHUB_OWNER: "kryptokrona"
  GH_TOKEN: ${{ secrets.YGGDRASIL_GH_TOKEN }}

on:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - ".run/**"

jobs:
  build:
    name: "Build: ${{ matrix.config.name }} / ${{ matrix.config.platform }}"
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: true
      matrix:
        config:
          - { name: "Windows Latest", os: windows-latest, platform: x64 }
          - { name: "Ubuntu Latest", os: ubuntu-latest, platform: x64 }

    env:
      PLATFORM: ${{ matrix.config.platform }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Choose Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.0

      - name: Install dependencies
        run: npm install --quiet

      - name: Build ${{ matrix.config.name }}
        if: matrix.config.os == 'windows-latest'
        run: npm run build:win-x64

      - name: Build ${{ matrix.config.name }}
        if: matrix.config.os == 'ubuntu-latest'
        run: npm run build:linux-$PLATFORM

      - name: "Upload ${{ matrix.config.name }} Artifact"
        uses: actions/upload-artifact@v3
        if: matrix.config.os == 'windows-latest'
        with:
          name: windows-latest
          path: |
            dist/*.exe

      - name: "Upload ${{ matrix.config.name }} Deb Artifact"
        uses: actions/upload-artifact@v3
        if: matrix.config.os == 'ubuntu-latest'
        with:
          name: ubuntu-latest-deb
          path: |
            dist/*.deb

      - name: "Upload ${{ matrix.config.name }} Snap Artifact"
        uses: actions/upload-artifact@v3
        if: matrix.config.os == 'ubuntu-latest'
        with:
          name: ubuntu-latest-snap
          path: |
            dist/*.snap
